leftnav:
- identifier: 28baa9ae-614d-5acb-913b-3cd5323f44c3
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 04974092-2e60-1f92-f3bb-c5184857c635
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: f6816877-ee72-4ff9-e594-f0771eaa96bb
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 84c22f7c-e328-142d-947e-896af650a12f
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: d1a532c8-aabc-bd41-7813-cf1cadc50ff9
  name: Exams
  pageRef: /pages/exams
  weight: 50
